@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGZiYTc4ZjY5ZTRhMTExN2U4ZmFkNiIsImVtYWlsIjoibWFuaEBnbWFpbC5jb20iLCJpYXQiOjE3NzY0Mjk0ODcsImV4cCI6MTc3NjUxNTg4N30.3_ubL4R8LDlVw25pwoWENRqgPAqYx0NxdHsIPRUgSSk
@productID = 69e229c4c6e08dd628bd28b0

### sign up
POST {{baseUrl}}/api/auth/sign_up
Content-Type: application/json

{
  "name": "Manh",
  "email": "manh@gmail.com",
  "password": "123"
}

### sign in (copy token from response and paste into @token)
POST {{baseUrl}}/api/auth/sign_in
Content-Type: application/json

{
  "email": "manh@gmail.com",
  "password": "123"
}

### create product (copy product._id and paste into @productID)
POST {{baseUrl}}/api/product
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Shirt test",
  "cost": 300,
  "describe": "product for cart/order test"
}

### get product
GET {{baseUrl}}/api/product
Authorization: Bearer {{token}}

### add to cart
POST {{baseUrl}}/api/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productID": "{{productID}}"
}

### get cart
GET {{baseUrl}}/api/cart
Authorization: Bearer {{token}}

### create order from cart
POST {{baseUrl}}/api/order
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### get order
GET {{baseUrl}}/api/order
Authorization: Bearer {{token}}
